version: 2
updates:
- package-ecosystem: maven
  directory: "/images/pmd_cpd"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/images/pylint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/images/phinder"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/images/stylelint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: strong_json
    versions:
    - ">= 0"
- package-ecosystem: docker
  directory: "/images/shellcheck"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/rubocop"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/scss_lint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/rails_best_practices"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/images/phpmd"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/images/code_sniffer"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/images/eslint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/images/tyscan"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/images/checkstyle"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/images/golangci_lint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/images/hadolint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/images/detekt"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/images/cpplint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/images/remark_lint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/images/pmd_java"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/images/ktlint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/querly"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/images/flake8"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/reek"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/haml_lint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/goodcheck"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/images/brakeman"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: brakeman
    versions:
    - "> 4.3.1, < 5"
- package-ecosystem: npm
  directory: "/images/tslint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/images/jshint"
  schedule:
    interval: weekly
    time: '09:00'
    timezone: Japan
  open-pull-requests-limit: 10
