name: Notify build to Bugsnag

on:
  push:
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/notify_build_to_bugsnag.sh
        env:
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          APP_VERSION: ${{ github.ref.replace(/\/refs\/tags\//, '') }}
          SOURCE_REVISION: ${{ github.sha }}
